// Generated by CoffeeScript 1.9.3
var GenericState;

GenericState = (function() {
  function GenericState(id, enteringConditions, loopFunction) {
    this.id = id;
    this.enteringConditions = enteringConditions;
    this.loopFunction = loopFunction;
  }

  return GenericState;

})();

(function() {
  function _Class() {}

  return _Class;

})();
