// Generated by CoffeeScript 1.9.3
var GenericState;

GenericState = (function() {
  function GenericState(id, enteringConditions, loopFunction) {
    this.id = id;
    this.enteringConditions = enteringConditions;
    this.loopFunction = loopFunction;
  }

  GenericState.prototype.executeState = function(callback) {
    this.loopFunction();
    return callback();
  };

  GenericState.prototype.testState = function() {
    return this.enteringConditions();
  };

  return GenericState;

})();
